#MAIL_USERNAME: 'cdvvrailstesting@gmail.com'
#MAIL_PASSWORD: 'iaukjyfjvohwydhw'
#MYSQL_USERNAME: 'administracion_so'
#MYSQL_PASSWORD: 'password'
MAIL_USERNAME: 'carlos.vargasvarela@ucr.ac.cr'
MAIL_PASSWORD: '*xVQ2#o!92H$4$'